export const overview = [
	{
		id: 1,
		icon: 'images/icon-facebook.svg',
		title: 'facebook icon',
		login: '@nathanf',
		usersTotal: 1987,
		usersType: 'followers',
		todayIcon: 'images/icon-up.svg',
		todayNum: '12',
		borderColor: '#1a8ef5',
	},
	{
		id: 2,
		icon: 'images/icon-twitter.svg',
		title: 'twitter icon',
		login: '@nathanf',
		usersTotal: 1044,
		usersType: 'followers',
		todayIcon: 'images/icon-up.svg',
		todayNum: '99',
		borderColor: '#1ca0f2',
	},
	{
		id: 3,
		icon: 'images/icon-instagram.svg',
		title: 'instagram icon',
		login: '@realnathanf',
		usersTotal: '11k',
		usersType: 'followers',
		todayIcon: 'images/icon-up.svg',
		todayNum: '1099',
		borderColor: 'linear-gradient(90deg, hsl(37, 97%, 70%), hsl(329, 70%, 58%))',
	},
	{
		id: 4,
		icon: 'images/icon-youtube.svg',
		title: 'youtube icon',
		login: 'Nathan F.',
		usersTotal: 8239,
		usersType: 'subscribers',
		todayIcon: 'images/icon-down.svg',
		todayNum: '144',
		borderColor: '#c40329',
	},
]

export const today = [
	{
		id: 1,
		type: 'page views',
		socialIcon: 'images/icon-facebook.svg',
		number: 87,
		percentageIcon: 'images/icon-up.svg',
		percentageNum: 3,
	},
	{
		id: 2,
		type: 'likes',
		socialIcon: 'images/icon-facebook.svg',
		number: 52,
		percentageIcon: 'images/icon-down.svg',
		percentageNum: 2,
	},
	{
		id: 3,
		type: 'likes',
		socialIcon: 'images/icon-instagram.svg',
		number: 5462,
		percentageIcon: 'images/icon-up.svg',
		percentageNum: 2257,
	},
	{
		id: 4,
		type: 'profile views',
		socialIcon: 'images/icon-instagram.svg',
		number: '52k',
		percentageIcon: 'images/icon-up.svg',
		percentageNum: 1375,
	},
	{
		id: 5,
		type: 'retweets',
		socialIcon: 'images/icon-twitter.svg',
		number: '117',
		percentageIcon: 'images/icon-up.svg',
		percentageNum: 303,
	},
	{
		id: 6,
		type: 'likes',
		socialIcon: 'images/icon-twitter.svg',
		number: '507',
		percentageIcon: 'images/icon-up.svg',
		percentageNum: 553,
	},
	{
		id: 7,
		type: 'likes',
		socialIcon: 'images/icon-youtube.svg',
		number: '107',
		percentageIcon: 'images/icon-down.svg',
		percentageNum: 19,
	},
	{
		id: 8,
		type: 'total views',
		socialIcon: 'images/icon-youtube.svg',
		number: '1407',
		percentageIcon: 'images/icon-down.svg',
		percentageNum: 12,
	},
]
